[package]
name = "iced_spinner"
authors = ["Iohann Rabeson"]
version = "0.1.0"
edition = "2021"

[dependencies]
iced_native = "0.9.1"

[dev-dependencies]
iced = "0.8.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
