[package]
name = "iced_spinner"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.8.0"
iced_native = "0.9.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
